# Generated by Django 2.2.6 on 2019-10-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='abbreviation',
            field=models.CharField(max_length=150, verbose_name='Abbreviation'),
        ),
    ]
