# Generated by Django 2.2.4 on 2019-10-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='statusstatus',
            new_name='status',
        ),
    ]
