# Generated by Django 2.2.4 on 2019-10-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='firstname',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=150, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(verbose_name='phone'),
        ),
    ]
