# Generated by Django 2.2.4 on 2019-10-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20191023_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit_card_number',
            field=models.BigIntegerField(verbose_name='Number credit card '),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.BigIntegerField(verbose_name='Phone'),
        ),
    ]
