# Generated by Django 2.2.4 on 2019-10-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Author image'),
        ),
    ]
